### ISSUE TITLE
Trigger at elevation not working

### ISSUE THREAD

**Issue by Spartacus68** [pnbruckner/ha-sun2#100]
Hi,

I am trying to trigger on time_at_elevation but it is not working. Is this an issue or isnßt in working yet?

```
alias: SU_Eingangslicht_SU_SA
description: ""
trigger:
  - platform: time
    at: sensor.su_eingang
    id: Sonnenuntergang
  - platform: time
    at: sensor.sa_eingang
    id: Sonnenaufgang
```

in sun2.yaml:
```
      - time_at_elevation: -1.5
        direction: setting 
        icon: mdi:weather-sunset-down
        name: SU_Eingang
      - time_at_elevation: -1.5
        direction: rising 
        icon: mdi:weather-sunset-up
        name: SA_Eingang
```

**Comment by pnbruckner** [comment]
What version of sun2 are you using?

**Comment by pnbruckner** [comment]
Glad you got it working!

> Is there an easy way to define customized daylight and night with sun2?

Not directly with the sun2 integration. However, it would be very simple to do with a template sensor:
```yaml
template:
  - sensor:
      - name: Daylight
        unique_id: custom_daylight
        device_class: duration
        state_class: measurement
        unit_of_measurement: hr
        state: >
          {{
            (states('sensor.su_eingang')|as_datetime - states('sensor.sa_eingang')|as_datetime)
            .total_seconds()/3600
          }}
```
> Or how can I create a condition which is true during "night" respective "daylight"?

Not exactly sure what you mean by "a condition". Do you mean an automation condition?

You could create a `binary_sensor` that is `on` (i.e., true) during your custom daylight, and another for night. E.g.,
```yaml
template:
  - binary_sensor:
      - name: Day
        unique_id: custom_day
        state: >
          {{ states('sensor.sa_eingang')|as_datetime < now() <= states('sensor.su_eingang')|as_datetime }}
      - name: Night
        unique_id: custom_night
        state: "{{ is_state('binary_sensor.day', 'off') }}"
```
Then you could use those for automation conditions.
