### ISSUE TITLE
Sun2 configuration file is not loaded

### ISSUE THREAD

**Issue by Spartacus68** [pnbruckner/ha-sun2#102]
Hi Phil,

sorry for that, but I am totally lost with the new sun2. I have setup a new HA only for testing sun2. I installed the integration and it configures sun2 entities automatically without using my local configuration.

Here is my config:
in configuarion.yaml:
 ` packages: !include_dir_named integrations`

in the folder integrations, I have the file sun2.yaml with the content from you example:
```
sun2:
  - unique_id: xxx
    binary_sensors:
      - unique_id: bs1
        elevation: horizon
      - unique_id: bs2
        elevation: 3
      - unique_id: bs3
        elevation: -6
        name: Above Civil Dawn
    sensors:
      - unique_id: s1
        time_at_elevation: 10
      - unique_id: s2
        time_at_elevation: -10
        direction: setting
        icon: mdi:weather-sunset-down
        name: Setting past 10 deg below horizon
      - unique_id: s3
        elevation_at_time: '12:00'
        name: Elv @ noon
      - unique_id: s4
        elevation_at_time: input_datetime.test
        name: Elv @ test var
```
But all the entities will not be created. What is wrong here?

Spartacus.
