### ISSUE TITLE
Dynamically updated longitute/latitude

### ISSUE THREAD

**Issue by wigster** [pnbruckner/ha-sun2#111]
I would like to use your integration to create a sun entity for a location which can change over time -- let's say the current location when I am on vacation. Would it be possible to set the longitude/latitude of the sensors from some input_number entity?

**Comment by pnbruckner** [comment]
Yes, something like that could be possible. But besides latitude & longitude, it would also need elevation and time_zone. Elevation could easily default to zero (which is the correct value in most cases.) And for time_zone, that could come from my [Entity Time Zone Sensor](https://github.com/pnbruckner/ha-entity-tz) custom integration.

Probably the best way to do this would be to allow templates for those four config options. That way it could get the values from anyplace. E.g. (in YAML):
```yaml

sun2:
  - unique_id: my_location
    location: My location
    latitude: "{{ state_attr('device_tracker.me', 'latitude') }}"
    longitude: "{{ state_attr('device_tracker.me', 'longitude') }}"
    time_zone: "{{ states('sensor.me_time_zone') }}"
    elevation: 0
```
I can tell you, though, this would be a lot of work. Couldn't you just create a temporary Sun2 entry for your vacation location?

**Comment by wigster** [comment]
I am currently deleting my "alternative" location integrations and recreating them, but I was hoping that it's possible to have this be automatised. As it is, it's enough work for me to only really do it when I am going for a big holiday, but I never to it for small trips. But we can't have all the candy in the world. Anyway, it would be a nice to have.

Thanks a lot for thinking about it.

**Comment by pnbruckner** [comment]
I'll leave this open because I do see that this could be a useful feature.

The problem is more, though, than just the amount of work to implement it. Most of the code needed is already in place, because if you configure it to use HA's location configuration (i.e., your Home location, time zone, etc.) it will update if those general system settings are changed. The downside, though, is there is a lot for it to do when this happens. It's not that big of a deal for something like this that doesn't change very often, if ever. But if it was tied to the location of, say, a `device_tracker` entity, that code would have to run a lot, and it could become a fairly large performance burden on the system, especially if it was done for several trackers. I haven't really measured how long the code would have to run when a location changes, so I'm not really sure how bad it would be, or what I'd have to do to make it reasonable. It wasn't really designed/written with this type of use in mind, so that would probably be the hardest part.

**Comment by pnbruckner** [comment]
@wigster what about an option to create an integration entry based on data provided by a service? I.e., maybe it would start with some initial location values (HA's or static values the user enters), and then it registers a service that can be called to update those values. E.g., `sun2.update_xyz`, where xyz is the name of the integration entry, and it would accept location data. E.g.,
```yaml
service: sun2.update_xyz
data:
  latitude: ...
  longitude: ...
  time_zone: ...
  elevation: ...
```
It would also remember those values across restarts.
