### ISSUE TITLE
Sun2 not working after update

### ISSUE THREAD

**Issue by Spartacus68** [pnbruckner/ha-sun2#123]
Hi,

what has changed with the new version, all my configurend sensors are not working anymore! How can I fix it?

```
sun2:
  - unique_id: xxxxx
    location: home
    latitude: 51.xxxxx
    longitude: 7.xxxxx
    elevation: 135
    time_zone: Europe/Berlin
    #binary_sensors:
    #  - unique_id: sun.gartenlicht
    #    elevation: -3
    #  - unique_id: sun.buergerlich
    #    elevation: -6
    sensors:
      - unique_id: su1
        time_at_elevation: -2.5
        direction: setting
        name: su1
        icon: mdi:weather-sunset-down
      - unique_id: su2
        time_at_elevation: -2.0
        direction: setting
        name: su2
        icon: mdi:weather-sunset-down        
      - unique_id: su3
        time_at_elevation: -1.5
        direction: setting
        name: su3
        icon: mdi:weather-sunset-down
      - unique_id: su4
        time_at_elevation: -0.9
        direction: setting
        name: su4
        icon: mdi:weather-sunset-down
      - unique_id: su5
        elevation_at_time: '00:00'
        name: Elevation at Datum

#
      - unique_id: sa1
        time_at_elevation: -4.0
        direction: rising
        name: sa1
        icon: mdi:weather-sunset-up
      - unique_id: sa2
        time_at_elevation: -1.5
        direction: rising
        name: sa2
        icon: mdi:weather-sunset-up
      - unique_id: sa3
        time_at_elevation: 0
        direction: rising
        name: sa3
        icon: mdi:weather-sunset-up
```

![image](https://github.com/pnbruckner/ha-sun2/assets/121975453/3ed65dd2-8cb9-4dc4-a2cf-c0bb3ac35648)
![image](https://github.com/pnbruckner/ha-sun2/assets/121975453/885fb8cb-a673-4c60-afbc-4676f613fda0)

**Comment by Spartacus68** [comment]
I changed back to 3.2 and now everything is working. Can you please explain, why my sensors are not working with 3.3?

**Comment by pnbruckner** [comment]
What HA Core version are you using? Any error or warning messages?

**Comment by pnbruckner** [comment]
Never mind. I see what's wrong. I'll have a fix out shortly.

**Comment by Spartacus68** [comment]
HA Version:

![image](https://github.com/pnbruckner/ha-sun2/assets/121975453/ebe1a795-2c71-4da4-97a9-7cd244d0bf84)

I cannot find anything in the system log, but it looks like, that the sun2.yaml was not loaded by your new version.  There was a blank configuration unter "integrations"

What I can do within the next days: I can clone the Homeassistant VM and can check it again

The setup:
![image](https://github.com/pnbruckner/ha-sun2/assets/121975453/b8dd8d97-1267-432d-b881-a5ad6e9ec4a0)
![image](https://github.com/pnbruckner/ha-sun2/assets/121975453/58321dd1-365c-4a34-849e-2ee8ed763cac)

```
sun2:
  - unique_id: villigst
    location: home
    latitude: 51.429671
    longitude: 7.595837
    elevation: 135
    time_zone: Europe/Berlin
    #binary_sensors:
    #  - unique_id: sun.gartenlicht
    #    elevation: -3
    #  - unique_id: sun.buergerlich
    #    elevation: -6
    sensors:
      - unique_id: su1
        time_at_elevation: -2.5
        direction: setting
        name: su1
        icon: mdi:weather-sunset-down
      - unique_id: su2
        time_at_elevation: -2.0
        direction: setting
        name: su2
        icon: mdi:weather-sunset-down        
      - unique_id: su3
        time_at_elevation: -1.5
        direction: setting
        name: su3
        icon: mdi:weather-sunset-down
      - unique_id: su4
        time_at_elevation: -0.9
        direction: setting
        name: su4
        icon: mdi:weather-sunset-down
      - unique_id: su5
        elevation_at_time: '00:00'
        name: Elevation at Datum

#
      - unique_id: sa1
        time_at_elevation: -4.0
        direction: rising
        name: sa1
        icon: mdi:weather-sunset-up
      - unique_id: sa2
        time_at_elevation: -1.5
        direction: rising
        name: sa2
        icon: mdi:weather-sunset-up
      - unique_id: sa3
        time_at_elevation: 0
        direction: rising
        name: sa3
        icon: mdi:weather-sunset-up
```
