### ISSUE TITLE
Sensors for golden hour and blue hour

### ISSUE THREAD

**Issue by voidzero** [pnbruckner/ha-sun2#129]
I was wondering if it's possible for you to add sensors for golden hour and blue hour. It would be eight additional sensors: blue/golden hour, dusk/dawn, start/end.

That way I could add them to my dashboard.

**Comment by voidzero** [comment]
Just thinking out loud -- this morning I noticed that golden hour is taking too long:

![image](https://github.com/user-attachments/assets/d02d4936-312a-4b23-b400-0a71e1ed16a7)


I'm going by the times as displayed in my Mobile Observatory Android app. Here's a screenshot for that:

![Screenshot_2024-08-05-14-07-19-36_7e775883f61c9a1dada066700d5a3400](https://github.com/user-attachments/assets/1ec995cb-8926-41db-88f8-ab948a0bf12a)

So golden hour for today at my location, according to this app, would be from 6:03 to 7:16 (elevation of the sun is between 0° and 10°) and tonight from 20:02 to 21:14.
Blue hour would be from between 4:57 and 5:48, and in the evening from 21:29 to 22:20 (elevation is between 8° and 2° below the horizon).

**Comment by pnbruckner** [comment]
> I was wondering if it's possible for you to add sensors for golden hour and blue hour. It would be eight additional sensors: blue/golden hour, dusk/dawn, start/end.
> 
> That way I could add them to my dashboard.

The phase sensor has three attributes -- `blue_hour`, `golden_hour` & `rising` -- that you could use to create (binary) template sensors. Would that help?

Or do you really need sensors that indicate when each of these periods start & end?

**Comment by pnbruckner** [comment]
> Just thinking out loud -- this morning I noticed that golden hour is taking too long:
> 
> ![image](https://private-user-images.githubusercontent.com/1332504/355094421-d02d4936-312a-4b23-b400-0a71e1ed16a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NjA1MDYsIm5iZiI6MTcyMzU2MDIwNiwicGF0aCI6Ii8xMzMyNTA0LzM1NTA5NDQyMS1kMDJkNDkzNi0zMTJhLTRiMjMtYjQwMC0wYTcxZTFlZDE2YTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMTQ0MzI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhjZjlkZDI4YmJlMWI1ZWZmNTQ3ZTIyNDI4YjM2NTMzMWY1OWU3OGY5ZjlhMzRiY2ZiMDc2ZGEwMGJjNGRmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2zNH97EXunZMsVgGHKg-BCKh8iaUSzXxx5sWghpjsEs)

It looks like you're using Sun2's "deCONZ Daylight" sensor. That sensor was designed to mimic HA's built-in [deCONZ Daylight Sensor](https://www.home-assistant.io/integrations/deconz/#deconz-daylight-sensor). Even though the description implies the state is `golden_hour_1` during the morning golden hour, that's not how it actually works. I think that sensor is very misleading, but like I said, it was made to mimic an already existing sensor. Someone had asked for that a long time ago because they had used the deCONZ Daylight Sensor for a long time, had automations based on it, but for whatever reason couldn't use the real integration anymore. So, I obliged and created this sensor. I don't actually think it's very useful. Which is why I created the phase sensor which I believe is much more useful.

> So golden hour for today at my location, according to this app, would be from 6:03 to 7:16 (elevation of the sun is between 0° and 10°)

That's not the definition of golden hour that I have seen. FYI, the phase sensor (and its attributes) are based on blue hour being defined as the sun's elevation between -6 & -4 degrees, and golden hour being between -4 & +6 degrees.

**Comment by pnbruckner** [comment]
@voidzero you could also do what was suggested here:

https://community.home-assistant.io/t/enhanced-sun-component/63553/658

**Comment by voidzero** [comment]
Hi Phil:

Much thanks and sorry for the delay with replying, I became very ill, my situation is improving now. I'll have a look and check back in. Thanks.

**Comment by pnbruckner** [comment]
No problem. Sorry to hear you've been ill, and glad to hear your condition is improving! Let me know if you have any other questions, or if you'd need help implementing any of the suggestions.

**Comment by pnbruckner** [comment]
> By the way, is this integration compatible with HACS version >= 2?

I have no idea. I haven't tried upgrading HACS yet.

**Comment by pnbruckner** [comment]
@voidzero can you provide an update on the current status of your original request?

**Comment by voidzero** [comment]
Hi Phil I'm sorry for the delay. Stuff got much worse here but hopefully I'm on the rebound now. (Crohn's and related immune system shenanigans)

I don't have time for it today but I'll pick it up this week and follow up, is that okay?

Btw - I can confirm it's fully compatible with hacs 2 or at least I haven't had issues since upgrading.

**Comment by voidzero** [comment]
Here is the configuration I wrote based on the link you provided where someone posted their json. This should be sufficient to allow people to create their automation on.

```
sun2:
  - unique_id: Home
    location: YOUR_CITY
    latitude: YOUR_LAT
    longitude: YOUR_LONG
    time_zone: Europe/Amsterdam
    sensors:
      - unique_id: bh_rising_start
        name: Blue Hour Rising (start)
        time_at_elevation: -6.0
        direction: rising
        icon: mdi:weather-sunset-down
      - unique_id: gh_rising_start
        name: Blue Hour Rising (end) / Golden Hour Rising (start)
        time_at_elevation: -4.0
        direction: rising
        icon: mdi:weather-sunset-down
      - unique_id: gh_rising_end
        name: Golden Hour Rising (end)
        time_at_elevation: 6.0
        direction: rising
        icon: mdi:weather-sunset-down

      - unique_id: gh_setting_start
        name: Golden Hour Setting (start)
        time_at_elevation: 6.0
        direction: setting
        icon: mdi:weather-sunset-down
      - unique_id: bh_setting_start
        name: Golden Hour Setting (end) / Blue Hour Setting (start)
        time_at_elevation: -4.0
        direction: setting
        icon: mdi:weather-sunset-down
      - unique_id: bh_setting_end
        name: Blue Hour Setting (end)
        time_at_elevation: -6.0
        direction: setting
        icon: mdi:weather-sunset-down

```

**Comment by schnillerman** [comment]
> > I was wondering if it's possible for you to add sensors for golden hour and blue hour. It would be eight additional sensors: blue/golden hour, dusk/dawn, start/end.
> > That way I could add them to my dashboard.
> 
> The phase sensor has three attributes -- `blue_hour`, `golden_hour` & `rising` -- that you could use to create (binary) template sensors. Would that help?
> 
> Or do you really need sensors that indicate when each of these periods start & end?

Hi @pnbruckner, I'm trying your suggestion, but the following template code won't work:

```yaml
binary_sensor:
  - name: Golden Hour BS
    state: "{{ state_attr('sensor.mtv_1_sun_phase', 'golden_hour') }}"
```

Entering ``{{ state_attr('sensor.mtv_1_sun_phase', 'golden_hour') }}`` in the developer tools in the template tab returns true/false correctly.

Can you please advise?
