### ISSUE TITLE
Additional attributes for Time at Elevation Sensor

### ISSUE THREAD

**Issue by heinemannj** [pnbruckner/ha-sun2#131]
Please add new sensor's attributes e.g.

```
time_at_elevation: xxx
direction: xxx
```

to Time at `Elevation Sensors`.

I'm using the following YAML package:

```
# ########## Sun2 Integration ##########
#
# sun2-package.yaml
#
# - sensor.hems_sun_prediction_end
# - sensor.hems_sun_pv_excess_end
# - sensor.hems_sun_pv_excess_start
#
sun2:
  - unique_id: hems
    sensors:
      - unique_id: prediction_end
        time_at_elevation: 25
        direction: setting
        icon: mdi:weather-sunset-down
        name: Prediction end
      - unique_id: pv_excess_end
        time_at_elevation: 5
        direction: setting
        icon: mdi:weather-sunset-down
        name: PV excess end
      - unique_id: pv_excess_start
        time_at_elevation: 15
        direction: rising
        icon: mdi:weather-sunset-up
        name: PV excess start
```
 
Expected output:

![image](https://github.com/user-attachments/assets/f3434aab-4b81-46e0-b98d-407d1e081f10)

I'm using your integration as a core component for an Home Energy Management System (HEMS).
This additional config info within the sun2 sensors state will simplify debugging a lot.
