### ISSUE TITLE
azimuth_at_time

### ISSUE THREAD

**Issue by DavidAntonin** [pnbruckner/ha-sun2#133]
Hello, we already have elevation_at_time, can you please implement azimuth_at_time. Thank you

**Comment by pnbruckner** [comment]
@DavidAntonin, please review issue #120, then let me know if you still want an azimuth_at_time sensor, and if so, please explain your use case.

**Comment by heinemannj** [comment]
Not 100% the same request but going into the same direction:  `sun2 time_at_azimuth` sensors

I'm developing right now an Home Energy Management System (HEMS) https://github.com/heinemannj/huawei_solar_hems .

I have to calculate several setpoints for today and for tomorrow to provide EMHASS https://github.com/davidusb-geek/emhass an prediction horizon for tomorrow afternoon/evening :

```
          sun_rising_time_today: "{{ state_attr('sensor.hems_sun_rising', 'today')|as_datetime|as_local }}"
          sun_setting_time_today: "{{ state_attr('sensor.hems_sun_setting', 'today')|as_datetime|as_local }}"
          solar_noon_time_today: "{{ state_attr('sensor.hems_sun_solar_noon', 'today')|as_datetime|as_local }}"
          prediction_end_time_today: "{{ state_attr('sensor.hems_sun_prediction_end', 'today')|as_datetime|as_local }}"
          prediction_end_time_tomorrow: "{{ state_attr('sensor.hems_sun_prediction_end', 'tomorrow')|as_datetime|as_local }}"
          pv_excess_start_time_today: "{{ state_attr('sensor.hems_sun_pv_excess_start', 'today')|as_datetime|as_local }}"
          pv_excess_end_time_today: "{{ state_attr('sensor.hems_sun_pv_excess_end', 'today')|as_datetime|as_local }}"
```
 
  Actually I'm using sun2 `time_at_elevation` sensors, but obviously this will not work for an SSE PV orientation (-41°):
  
```
  sun2:
  - unique_id: hems
    sensors:
      - unique_id: prediction_end
        time_at_elevation: 25
        direction: setting
        icon: mdi:weather-sunset-down
        name: Prediction end
      - unique_id: pv_excess_end
        time_at_elevation: 15
        direction: setting
        icon: mdi:weather-sunset-down
        name: PV excess end
      - unique_id: pv_excess_start
        time_at_elevation: 15
        direction: rising
        icon: mdi:weather-sunset-up
        name: PV excess start
```

Above based on `sun2 time_at_azimuth` sensors will solve the issue in an perfect way.
Please support this feature request - From my perspective it really make sense.
