### ISSUE TITLE
Adding ability to specify lat/long dynamically

### ISSUE THREAD

**Issue by DanClarke-io** [pnbruckner/ha-sun2#141]
Hello!

I currently use Home Assistant in my van, and as we travel I would like to know for whatever location we're in, when sunset is etc. I've tried to use this integration to specify the lat/long from my GPS tracker, but I keep getting errors, I don't think it currently supports templating?

I've tried this:
```
template:
  - sensor:
      - name: "journey_lat"
        state: "{{ state_attr('sensor.journey_device_tracker', 'lat') }}"
        unit_of_measurement: "°"
      - name: "journey_long"
        state: "{{ state_attr('sensor.journey_device_tracker', 'long') }}"
        unit_of_measurement: "°"
```

```
sun2:
  - name: Van
    latitude: sensor.journey_lat
    longitude: sensor.journey_long
    elevation: 0
```

But I keep getting the same sort of error:
`Invalid config for 'sun2' at configuration.yaml, line 14: some but not all values in the same group of inclusion 'location' 'sun2->0-><location>', got None`

If I try to put within a location like this:
```
sun2:
  - name: Van
    location:
      latitude: "{{ states('sensor.journey_lat') | float(0) }}"
      longitude: "{{ states('sensor.journey_long') | float(0) }}"
      elevation: 0
```
I get this error:
`Invalid config for 'sun2' at configuration.yaml, line 15: some but not all values in the same group of inclusion 'location' 'sun2->0-><location>', got {'latitude': "{{ states('sensor.journey_lat') | float(0) }}", 'longitude': "{{ states('sensor.journey_long') | float(0) }}", 'elevation': 0}, `

Am I just coding it up wrong, or is this something that would need adding?

Thanks!

**Comment by DanClarke-io** [comment]
Apologies, I had the automation set up wrong:
```
action: sun2.update_location
data:
  location: Journey
  latitude: "{{ state_attr('sensor.journey_device_tracker','lat') }}"
  longitude: "{{ state_attr('sensor.journey_device_tracker','long') }}"
  time_zone: Europe/London
```
I just need to automate the timezone, and its sorted.
