### ISSUE TITLE
Sensor naming(?)

### ISSUE THREAD

**Issue by Tom-ahawk** [pnbruckner/ha-sun2#23]
Any chance to get an input parameter for the sensor which add a “name” to the sensor, like:

```
  - platform: sun2
    pre_name: "sun2_"
    monitored_conditions:
      - dawn
      - sunrise
      - solar_noon
      - sunset
      - dusk
      - daylight
      - night
      - elevation
      - max_elevation
      - min_elevation
```
Resulting in sensor names like:
sensor.sun2_elevation
sensor.sun2_max_elevation
sensor.sun2_min_elevation
sensor.sun2_dawn
sensor.sun2_sunrise
Just to be able to have a distinctive names for this package/sensor group (since it’s not default).

Cheers.

**Comment by pnbruckner** [comment]
That is already possible with [entity_namespace](https://www.home-assistant.io/docs/configuration/platform_options/#entity-namespace). E.g.:
```yaml
sensor:
- platform: sun2
  entity_namespace: sun2
  monitored_conditions:
  ...
```
