### ISSUE TITLE
astronomical sensors return 'incorrect' state

### ISSUE THREAD

**Issue by Mariusthvdb** [pnbruckner/ha-sun2#6]
please see: community post: https://community.home-assistant.io/t/enhanced-sun-component/63553/227?u=mariusthvdb

in short using:
```
sensor:
# https://github.com/pnbruckner/ha-sun2
  - platform: sun2
    entity_namespace: astro
    monitored_conditions:
      - solar_midnight
      - astronomical_dawn
      - nautical_dawn
      - dawn
      - sunrise
      - solar_noon
      - sunset
      - dusk
      - nautical_dusk
      - astronomical_dusk
      - daylight
      - civil_daylight
      - nautical_daylight
      - astronomical_daylight
      - night
      - civil_night
      - nautical_night
      - astronomical_night
```

gives:
![Schermafbeelding 2019-06-22 om 15 04 57](https://user-images.githubusercontent.com/33354141/59964276-26cc3800-94ff-11e9-8f28-9f1c9670ea2b.jpg)
![Schermafbeelding 2019-06-22 om 15 05 39](https://user-images.githubusercontent.com/33354141/59964288-3e0b2580-94ff-11e9-9c38-2a0a1827468c.jpg)

The 'Invalid Date' and 'Unknown' seem to indicate a config error, while in fact they are unknown, because astronomical sensors are for when the sun is 18° below the horizon, which does not happen at my location at this time of the year (at least.) 

so not a bug, but a misleading state. If this is beyond the integration (because the frontend handles the state display) this unfortunate. If a 'not set' or 'not available' could be displayed, that would describe the state more precisely.
if not possible, ill close.
thanks for a great (again) integration.
