### ISSUE TITLE
Request/Enhancement: Enable entities to exist as Date/Time helpers

### ISSUE THREAD

**Issue by FirstRulez** [pnbruckner/ha-sun2#61]
The purpose of this request is so that I can use these date/time sensors within Automations and they are selectable as a Date/Time helper in an Automation Condition

![image](https://user-images.githubusercontent.com/32237385/163024226-0b9b1300-8613-4701-b8ef-735fcdc015c0.png)

**Comment by pnbruckner** [comment]
According to the [docs](https://next.home-assistant.io/docs/scripts/conditions/#time-condition) you can already do this:

> or another sensor entity containing a timestamp with the “timestamp” device class, can be used instead.

E.g., I just tried this:
```yaml
automations:
- trigger:
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    before: sensor.sunset
  action:
  - event: TEST
```
And it fired the event.

The problem seems to be the frontent. It's only allowing selection of `input_datetime` entities when it should also allow `sensor` entities that have a `timestamp` device class (which the sun2 "point in time" sensors do. have) You should open an issue with HA (or its frontend.)
