### ISSUE TITLE
Sun_Phase Sensor not updating correctly

### ISSUE THREAD

**Issue by rlewis187** [pnbruckner/ha-sun2#68]
For a couple of days my sun phase sensor has been failing to update correctly in the morning. 

It is just missing out some of the phases, I still get updates at noon and in the evening, but its staying at night until solar noon. 
Error log:
```
This error originated from a custom integration.

Logger: custom_components.sun2.sensor
Source: custom_components/sun2/sensor.py:125
Integration: sun2
First occurred: November 4, 2022 at 23:52:43 (6 occurrences)
Last logged: November 4, 2022 at 23:52:43

London Sun Phase: Failed to find the time at elev: -12.000
London Sun Phase: Failed to find the time at elev: -6.000
London Sun Phase: Failed to find the time at elev: -4.000
London Sun Phase: Failed to find the time at elev: -0.833
London Sun Phase: Failed to find the time at elev: 6.000

```
my .yaml configuration:
```

- platform: sun2
  entity_namespace: London
  latitude: #########
  longitude: ########
  time_zone: Europe/London
  elevation: 11
  monitored_conditions:
    - sunrise
    - sunset
    - sun_phase
    - dawn
    - dusk
    - solar_noon
    - solar_midnight
    - daylight
    - night

```

**Comment by pnbruckner** [comment]
@rlewis187 thanks for letting me know!

Could you please enable debug for this integration, restart HA, and look for any messages in home-assistant.log related to this? In particular, after the error message, you should see something like this:
```text
2022-11-05 10:01:22 DEBUG (MainThread) [custom_components.sun2.sensor] Sun2 Sun Phase: tL = 2022-11-05 00:36:22-05:00/-64.182, cur = 2022-11-05 10:01:22-05:00/22.269, tR = 2022-11-05 12:36:21-05:00/32.421, rising = True
```
If you can share those messages, or at least one of them, I can try to figure out the problem from that. It might, however, help if you could share the latitude & longitude you're using. You can send that to me via a private message either on the HA community forum (user pnbruckner), or via e-mail (pnbruckner@gmail.com.)

**Comment by rlewis187** [comment]
Thanks for the fast response!

I emailed you my Lat/Long info.

Sorry, I'm a hardware guy, I only play with this kind of thing, can you please tell me how to enable debugging for this integration?

I should also add that a restart of HA does force an update to the correct value.

**Comment by pnbruckner** [comment]
> I emailed you my Lat/Long info.

Thanks! I'll add those to my test system.

> can you please tell me how to enable debugging for this integration?

Sure. Add the following to your configuration.yaml file:
```yaml
logger:
  default: info
  logs:
    custom_components.sun2: debug
```
For more details on configuring the logger:

https://www.home-assistant.io/integrations/logger/

> I should also add that a restart of HA does force an update to the correct value.

Ok, that's interesting. But do the errors always come back, and if so, approximately when? Are there other errors that typically precede these errors?

Basically, let me know whatever you think will help me to reproduce the errors. Also, what version of HA are you running?
