### ISSUE TITLE
Request additional timestamps 

### ISSUE THREAD

**Issue by Spartacus68** [pnbruckner/ha-sun2#75]
Hello,

I wanted to ask, if it is possible to create timestamps for user defined eleveation:
triggering on  specific elevation is possible, but the calculation of the respective timestamp can only be done for the next cycle.

In order to visualize the upcomming times, I would like to have the timestamps for the last cycles, as you have it for dusk and dawn (yesterday, today, tomorrow)

I found no support for this feature, maybe it is possible to consider, if this can be implemented in one of the next releases.

Spartacus

**Comment by pnbruckner** [comment]
Yes, this is a good idea, and fairly straightforward. The hardest part is adding the schema and documentation. lol!

I've already implemented the new feature. See associated PR. Feel free to give it a try or wait until I release a beta (after I add the documentation for the new sensor option.) If you do give it a try, I'd appreciate any feedback.

Basically, add something like this to your config:
```yaml
sensor:
  - platform: sun2
    monitored_conditions:
      - time_at_elevation: ELEVATION  # A float value
        direction: setting  # rising or setting, default is rising
        icon: mdi:weather-sunset-down  # Default is mdi:weather-sunny
        name: Setting at ELEVATION  # Default is "Rising/Setting at [minus] ELEVATION"
```

**Comment by Spartacus68** [comment]
Hello Phil,

thanks for the quick reply and I would really like to test this asap. 
But it seems that I am too stupid to implement this. Can you please give 
me a hint how to download the files I need to change in HA?
And how can I understand this!  Does it mean I can configure different 
elevations in my config?

like:

sensor:
- platform sun2
   - monitred_conditions
   - elevation
   - sun_phase
   - dawn

   - time_at_elevation: -3.4
       direction: setting
       name: Setting at -3,4° in the evening

   - time_at_elevation: -5.2
       direction: rising
       name: Rising at -5,2° in the morning


Thanks a lot,
Spartacus

------ Originalnachricht ------
Von "Phil Bruckner" ***@***.***>
An "pnbruckner/ha-sun2" ***@***.***>
Cc "Spartacus68" ***@***.***>; "Author" 
***@***.***>
Datum 21.02.2023 17:29:34
Betreff Re: [pnbruckner/ha-sun2] Request additional timestamps (Issue 
#75)

**Comment by Spartacus68** [comment]
Hi,

yeh! It works!
Give me some more time to test the whole functionality. I will reply asap!
Thanks a lot for this great feature!
Spartacus.

**Comment by pnbruckner** [comment]
@Spartacus68 

> Does it mean I can configure different elevations in my config?

Yes, you can add as many `time_at_evelation` sensor configurations as you like.

**Comment by Spartacus68** [comment]
@pnbruckner ,

yeh! You made my day!!

**Comment by Spartacus68** [comment]
Hello!

I checked the new **time_at_evaluation** and the timestamp of  my **sensor.sa_rollo** works perfectly.  But is it correct that no trigger event is generated when a certain evaluation/ time is reached?

I tried to trigger  on it like this, but it doesn´t work:
```
trigger:
  - platform: template
    value_template: "{{(state_attr('sensor.sa_rollo', 'today') )}}"
```

**Comment by pnbruckner** [comment]
Well, that certainly won't work, because for a template trigger to fire the template needs to render to `true`, which that, of course, won't.

I think what you want is:
```yaml
trigger:
  - platform: time
    at: sensor.sa_rollo
```
