### ISSUE TITLE
no sonsor is available after installation an setup

### ISSUE THREAD

**Issue by Zackzarack1** [pnbruckner/ha-sun2#85]
Hi,
I tried to use the integration.
I added and installed the extension via hacs as custom. The files are in the correct directory. I restarted Homeassistand and added the entries in my configuration.yaml and restarted again. But I can't find the sensor. My homeassistant version is: 2023.4.5 Here is my configuration:

```yaml
template: 
  - sensor:
    - platform: sun2
      entity_namespace: sun2Test
      monitored_conditions:
        - sunrise
        - sunset
        - sun_phase
```

Am I doing something wrong? Or can you send me an example configuration?

Best,
Sascha

**Comment by pnbruckner** [comment]
The configuration does not go under `template`. And `entity_namespace` is not required (although you can use it if you want.) Try:
```yaml
sensor:
  - platform: sun2
    monitored_conditions:
      - sunrise
      - sunset
      - sun_phase
```
