### ISSUE TITLE
time_at_elevation suddenly not working as expected.

### ISSUE THREAD

**Issue by SciFi-Bob** [pnbruckner/ha-sun2#97]
Hi there,

I had the below sensors being provided by Sun2.  It was working perfectly and then suddenly just stopped, does anyone know what I may be doing wrong?

Sensor Config is:

```yaml
- platform: sun2
  monitored_conditions:
    - sunrise
    - sunset
    - daylight
    - sun_phase
    - elevation
    - time_at_elevation: 13
      direction: rising
      name: PV sun rise
    - time_at_elevation: 25
      direction: setting
      name: PV sun set
```

The pv_sun_rise sensor works no problem but the pv_sun_set is returning 'Unknown'.

Thanks
